# Simple Kubernetes Pod to deploy the app contained in nigelpoulton/getting-started-k8s:1.0
apiVersion: v1  #apiVersion is the version of the API that the resource should use. Anytime you see a 1 like this, it means the feature is GA and considered stable.
kind: Pod #kind is the type of resource you are creating. In this case, it's a Pod. 
metadata:
  name: hello-pod #name is the name of the pod.
  labels:
    app: web #labels are used to identify the pod.
spec: #spec is the specification of the pod. 
  containers: #containers is the list of containers that will be run in the pod.
    - name: web-ctr #name is the name of the container.
      image: mhali2/getting-started-k8s:1.0 #image is the image to use for the container.
      ports:
        - containerPort: 8080 #ports is the list of ports that the container will listen on.
#Port needs to match the port the app is listening on.
#by default images are pulled from docker hub.
#if you want to pull from a private registry, you need to add the registry to the image.

